version: '3.5'

services:
  backend:
    build:
      context: ../../1/1.12/backend
      dockerfile: Dockerfile
    environment:
      - REDIS=cache
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
  frontend:
    build:
      context: ../../1/1.12/frontend
      dockerfile: Dockerfile
  cache:
    image: redis
    restart: unless-stopped
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
  web:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
