version: '3.5'

services:
  backend:
    build:
      context: ../../1/1.12/backend
      dockerfile: Dockerfile
    ports:
      - 8000:8000
    environment:
      - REDIS=cache
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
  frontend:
    build:
      context: ../../1/1.12/frontend
      dockerfile: Dockerfile
    ports:
      - 5000:5000
  cache:
    image: redis
    restart: unless-stopped
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
