version: '3.5'

services:
  backend:
    build: ext-ml-kurkkumopo-backend
    ports:
      - 5000:5000
    depends_on: 
      - training
  frontend:
    build: ext-ml-kurkkumopo-frontend
    ports:
      - 3000:3000
  training:
    build: ext-ml-kurkkumopo-training
    volumes: 
      - models:/src/model
      - imgs:/src/imgs
    restart: unless-stopped
    
volumes:
  models:
  imgs:
