version: '3.5'

services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      - REDIS=cache
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
  cache:
    image: redis
    restart: unless-stopped
    volumes:
      - ./cache:/data
  db:
    image: postgres
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./database:/var/lib/postgresql/data
  web:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
